name: simplefin_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  csv: ^6.0.0
  dotenv: ^4.2.0
  decimal: ^2.3.3
  http: ^1.2.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
