name: simplefin_dart
description: Dart client for the SimpleFIN API.
version: 0.1.0
repository: https://github.com/csells/simplefin_dart
homepage: https://github.com/csells/simplefin_dart

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.5.0
  csv: ^6.0.0
  decimal: ^3.2.4
  dotenv: ^4.2.0
  http: ^1.2.2

dev_dependencies:
  all_lint_rules_community: ^0.0.43
